#
# MIT License
#
# (C) Copyright [2021-2022] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
name: 'Generate, Attach, and Sign container image SBOM'
description: |
  Use Syft to generate a SPDX SBOM from a given container image. The SBOM artifact is attached to the 
  given container image in a registry using cosign, and cosign is used to sign the SBOM. 
inputs:
  cosign-version:
    required: false
    description: Version of cosign-release to use
    default: 'v1.4.1'
  cosign-gcp-project-id:
    required: true
    description: cosign project id in GCP
  cosign-gcp-sa-key:
    required: true
    description: cosign service account key in GCP
  cosign-key:
    required: true
    description: cosign key
  registry:
    required: false
    default: artifactory.algol60.net
    descriptions: Registry to push image SBOM
  registry-username:
    required: true
    description: Container registry username
  registry-password:
    required: true
    description: Container registry user password
  github-sha:
    required: true
    description: Github commit SHA used to build the image
  image:
    required: true
    description: Image to sign
outputs:
  sbom-location:
    description: Location in OCI Registry where the SBOM is located
    value: ${{ steps.sbom-location.outputs.value }}
runs:
  using: "composite"
  steps:
  - name: Install cosign
    uses: sigstore/cosign-installer@main
    with:
      cosign-release: ${{ inputs.cosign-version }}

  - name: Install Syft
    id: syft
    uses: anchore/sbom-action/download-syft@v0

  - name: Authenticate to Google Cloud
    uses: google-github-actions/auth@v0
    with:
      workload_identity_provider: projects/672506737953/locations/global/workloadIdentityPools/github-cray-hpe/providers/github
      service_account: cosign@sdlc-ops.iam.gserviceaccount.com
      create_credentials_file: false

  - name: Set up Cloud SDK
    uses: google-github-actions/setup-gcloud@v0

  - name: Login to Registry
    uses: docker/login-action@v2
    with:
      registry: ${{ inputs.registry }}
      username: ${{ inputs.registry-username }}
      password: ${{ inputs.registry-password }}
    
  - name: Generate SBOM
    shell: bash
    env:
      IMAGE: ${{ inputs.image }}
    run: syft -vv packages $IMAGE --output spdx  > container_image.spdx

  - name: Attach SBOM
    env:
      IMAGE: ${{ inputs.image }}
    shell: bash
    run: cosign attach sbom --sbom container_image.spdx $IMAGE

  - name: Triangulate SBOM image Location
    id: sbom-location
    env:
      IMAGE: ${{ inputs.image }}
    shell: bash
    run: echo "value=$(cosign triangulate --type sbom $IMAGE)" >> $GITHUB_OUTPUT

  - name: Sign SBOM
    env:
      COSIGN_KEY: ${{ inputs.cosign-key }}
      SBOM_LOCATION: ${{ steps.sbom-location.outputs.value }}
    shell: bash
    run: cosign sign --key $COSIGN_KEY -a GIT_HASH=$GITHUB_SHA $SBOM_LOCATION
