workflows_repository: .github
include_workflows_repository: true
exclude:
  repositories:
  - test-shared-libraries
  - falco
  - ilorest
  - metal-cloud-init
  - metal-ipxe
  - rekor-operator
  - wait-for-it
