#
# MIT License
#
# (C) Copyright [2021-2022] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
name: CSM Gitflow Mergeback PR Generator
description: Provides version, stable build id, and build timestamp
inputs:
  base-branch:
    required: true
    description: The pull request base branch
    default: develop
  source-branch:
    required: true
    description: The branch that needs to be merged back
    default: master
  pr-reviewers:
    required: false
    description: Default team or person to add as a reviewer to the pull request
    default: ''
  automerge:
    required: false
    description: Boolean on whether to set the PR to automerge (see conditions)
    default: false
  app-key:
    required: true
    description: The private key of the Github App who will create the pull request
  app-id:
    required: true
    description: The app id of the Github App that will create the pull request

outputs:
  pr-number:
    description: The number of the PR that was generated
    value: ${{ steps.cpr.outputs.pull-request-number }}
  pr-url:
    description: The url of the generated pull request
    value: ${{ steps.cpr.outputs.pull-request-url }}

runs:
  using: "composite"
  steps:

    - name: Get auth token for PR creation
      uses: navikt/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ inputs.app-key }}
        app-id: ${{ inputs.app-id }}

    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.base-branch }}
        token: ${{ steps.get-token.outputs.token }}

      # https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another
    - name: Reset target branch
      shell: bash
      run: |
        git fetch origin ${{ inputs.source-branch }}:${{ inputs.source-branch }}
        git reset --hard ${{ inputs.source-branch }}

    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ steps.get-token.outputs.token }}
        branch: mergeback-master-${{ github.event.pull_request.head.ref }}
        branch-suffix: timestamp
        base: ${{ inputs.base-branch }}
        delete-branch: true
        title: "[chore] ${{ inputs.source-branch }} -> ${{ inputs.base-branch }} from PR ${{ github.repository }}#${{ github.event.pull_request.number }} (${{ github.event.pull_request.head.ref }})"
        signoff: true
        assignees: ${{ github.actor }}
        committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
        author: "${{ github.event.pull_request.user.login }} <${{ github.event.pull_request.user.login }}@users.noreply.github.com>"
        labels: |
          gitflow-maintenance
        commit-message: >
          Autogenerated gitflow merge back from PR #${{ github.event.pull_request.number }}:
          * Head Branch: ${{ github.event.pull_request.head.ref }}
          * Autogenerated-by: [${{ github.workflow }} workflow #${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
        body: >
          Autogenerated gitflow merge back from PR #${{ github.event.pull_request.number }}:
          * Head Branch: ${{ github.event.pull_request.head.ref }}
          * Requested-by: @${{ github.event.pull_request.user.login }}
          * Autogenerated-by: [${{ github.workflow }} workflow #${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
        reviewers: |
          ${{ inputs.pr-reviewers }}

    - name: Enable Pull Request Automerge
      if: ( steps.cpr.outputs.pull-request-operation == 'created' ) && inputs.automerge
      uses: peter-evans/enable-pull-request-automerge@v1
      with:
        token: ${{ steps.get-token.outputs.token }}
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: merge

