name: Lint, test, and scan Helm charts

on:
  workflow_call:
    inputs:
      chart-dirs:
        description: Comma-separated list of directories that contain Helm charts
        type: string
        required: false
        default: charts
      test-charts:
        description: Test charts by deploying on a Kubernetes-in-Docker cluster
        type: boolean
        required: false
        default: true
      scan-charts:
        description: Template charts and scan Kubernetes resources with Snyk
        type: boolean
        required: false
        default: true
      scan-images:
        description: Scan container images with Snyk
        type: boolean
        required: false
        default: true
    secrets:
      snyk-token:
        description: Snyk authorization token
        required: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.list-changed.outputs.charts }}
      images: ${{ steps.extract-images.outputs.images }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        env:
          CHART_DIRS: ${{ inputs.chart-dirs }}
        run: echo "::set-output name=charts::$(ct list-changed --chart-dirs $CHART_DIRS | jq -R . | jq -sc .)"

      - name: Run chart-testing (lint)
        env:
          CHART_DIRS: ${{ inputs.chart-dirs }}
        run: ct lint --chart-dirs $CHART_DIRS

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: inputs.test-charts && fromJSON(steps.list-changed.outputs.charts)[0] != null

      - name: Run chart-testing (install)
        run: ct install
        if: inputs.test-charts

      - name: Extract images
        id: extract-images
        if: fromJSON(steps.list-changed.outputs.charts)[0] != null
        env:
          CHARTS: "${{ steps.list-changed.outputs.charts }}"
        shell: bash
        run: |
          jq -r '.[]' <<< "$CHARTS" | while read chart; do
            helm template release "$chart" --dry-run --replace --dependency-update | yq e -N '.. | .image? | select(.)' -
            helm show chart "$chart" | yq e '.annotations."artifacthub.io/images"' - | yq e -N '.[] | .image' -
          done | sort -u > extracted-images.txt
          echo "::set-output name=images::$(cat extracted-images.txt | jq -R . | jq -sc .)"

  scan-charts:
    # Equivalent to e.g.:
    #   ct list-changed --chart-dirs kubernetes | while read chart; do
    #     helm template release "$chart" --dry-run --replace --dependency-update > "${chart}/k8s-manifest.yaml"
    #     snyk iac test "${chart}/k8s-manifest.yaml"
    #   done
    needs: lint-test
    if: inputs.scan-charts && fromJSON(needs.lint-test.outputs.charts)[0] != null
    strategy:
      matrix:
        chart: ${{ fromJSON(needs.lint-test.outputs.charts) }}
      fail-fast: false
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1.1

      - name: Template chart (${{ matrix.chart }})
        run: helm template release ${{ matrix.chart }} --dry-run --replace --dependency-update > ${{ matrix.chart }}/k8s-manifest.yaml

      - name: Run Snyk to check Kubernetes resources (${{ matrix.chart }})
        uses: snyk/actions/iac@master
        #continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        with:
          file: ${{ matrix.chart }}/k8s-manifest.yaml

      #- name: Upload result to GitHub Code Scanning
      #  uses: github/codeql-action/upload-sarif@v1
      #  with:
      #    sarif_file: snyk.sarif

  scan-images: # to ensure dependent images are still free of CVEs
    needs: lint-test
    if: inputs.scan-images && fromJSON(needs.lint-test.outputs.images)[0] != null
    strategy:
      matrix:
        image: ${{ fromJSON(needs.lint-test.outputs.images) }}
      fail-fast: false
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk to check Docker image for vulnerabilities (${{ matrix.image }})
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        with:
          image: ${{ matrix.image }}

